# Generated by Django 5.0 on 2024-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_resumemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumemodel',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
