# Generated by Django 5.0 on 2024-09-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_intermediate_languagemodel_languagemodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='languagemodel',
            unique_together={('user', 'language')},
        ),
    ]
