# Generated by Django 5.0 on 2024-09-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_languagemodel_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagemodel',
            old_name='language',
            new_name='language_name',
        ),
        migrations.AlterUniqueTogether(
            name='languagemodel',
            unique_together={('user', 'language_name')},
        ),
    ]
