# Generated by Django 5.0 on 2024-09-22 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_language_languagemodel_language_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='intermediate_LanguageModel',
            new_name='intermediate_skillModel',
        ),
        migrations.RenameField(
            model_name='intermediate_skillmodel',
            old_name='language_name',
            new_name='my_skill_name',
        ),
        migrations.CreateModel(
            name='skillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=10, null=True)),
                ('proficiency_level', models.CharField(choices=[('high', 'High'), ('low', 'Low'), ('medium', 'Medium')], max_length=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill_name')},
            },
        ),
        migrations.DeleteModel(
            name='LanguageModel',
        ),
    ]
